language: node_js
node_js:
  - '10'

script:
  - yarn
  - yarn run build

install:
  - npm install -g firebase-tools

# safelist
branches:
  only:
    - master
    - develop

deploy:
  provider: script
  script: bash scripts/deploy.sh
# after_success:
#   - firebase use develop
#   - firebase deploy --token $FIREBASE_TOKEN
